version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./todo:/work

  # web:
  #   build: ./infra/node/
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./todo:/work
  #     - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   command: "npm run dev"
  #   working_dir: /work

  db:
    hostname: db
    build: ./infra/mysql
    ports:
      - 3306:3306
    volumes:
      - ./infra/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
